version: '3'
services:
  nextclouddev:
    build: .
    volumes:
      - ..:/var/www/html #:cached
      - /var/run/docker.sock:/var/run/docker-host.sock
    command: /bin/sh -c "/etc/init.d/apache2 start && while sleep 1000; do :; done"
    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:8080:8080
      - 127.0.0.1:8025:8025

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    network_mode: service:nextclouddev

  adminer:
    image: adminer
    restart: always
    network_mode: service:nextclouddev

  mailhog:
    image: mailhog/mailhog
    restart: always
    network_mode: service:nextclouddev
